//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeodesicasKML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeodesicasKML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fondo_GoogleEarth2 {
            get {
                object obj = ResourceManager.GetObject("fondo_GoogleEarth2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FondoAbout {
            get {
                object obj = ResourceManager.GetObject("FondoAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero que ha seleccionado no tiene un formato correcto.
        ///Revise el principio del KML..
        /// </summary>
        internal static string rsBadFileKMLFormatMsg {
            get {
                return ResourceManager.GetString("rsBadFileKMLFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero que ha seleccionado no tiene un formato correcto.
        ///Revise que sea un TXT..
        /// </summary>
        internal static string rsBadFilePRNFormatMsg {
            get {
                return ResourceManager.GetString("rsBadFilePRNFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero que ha seleccionado no tiene un formato correcto.
        ///Revise que sea un TXT..
        /// </summary>
        internal static string rsBadFileTXTFormatMsg {
            get {
                return ResourceManager.GetString("rsBadFileTXTFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;kml&gt;
        ///  &lt;Document&gt;
        ///    &lt;ScreenOverlay&gt;
        ///      &lt;name/&gt;
        ///      &lt;Icon/&gt;
        ///      &lt;overlayXY x=&quot;0&quot; y=&quot;1&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot; /&gt;
        ///      &lt;screenXY x=&quot;0.01&quot; y=&quot;0.99&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot; /&gt;
        ///      &lt;size x=&quot;0.05&quot; y=&quot;0&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot; /&gt;
        ///    &lt;/ScreenOverlay&gt;
        ///    &lt;Style id=&quot;pointStyle&quot;&gt;
        ///      &lt;IconStyle&gt;
        ///        &lt;color&gt;ffffffff&lt;/color&gt;
        ///        &lt;Icon&gt;
        ///          &lt;href/&gt;
        ///          &lt;x&gt;32&lt;/x&gt;
        ///          &lt;y&gt;0&lt;/y&gt;
        ///        &lt;/I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rsBaseKML {
            get {
                return ResourceManager.GetString("rsBaseKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FICHERO CREADO.
        /// </summary>
        internal static string rsCreatedFile {
            get {
                return ResourceManager.GetString("rsCreatedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero se ha generado !!.
        /// </summary>
        internal static string rsCreatedFileMsg {
            get {
                return ResourceManager.GetString("rsCreatedFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione dónde quiere grabar el fichero !!.
        /// </summary>
        internal static string rsFileDestionationMsg {
            get {
                return ResourceManager.GetString("rsFileDestionationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR CON EL FICHERO.
        /// </summary>
        internal static string rsFileError {
            get {
                return ResourceManager.GetString("rsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://.
        /// </summary>
        internal static string rsIconoWebUsuario {
            get {
                return ResourceManager.GetString("rsIconoWebUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //kml/Document/ScreenOverlay/size.
        /// </summary>
        internal static string rsLogoScalePath {
            get {
                return ResourceManager.GetString("rsLogoScalePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.05.
        /// </summary>
        internal static string rsLogoScaleX {
            get {
                return ResourceManager.GetString("rsLogoScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.08.
        /// </summary>
        internal static string rsLogoScaleY {
            get {
                return ResourceManager.GetString("rsLogoScaleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string rsName {
            get {
                return ResourceManager.GetString("rsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre para los puntos.
        /// </summary>
        internal static string rsNameTittle {
            get {
                return ResourceManager.GetString("rsNameTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que nombre le ponemos?.
        /// </summary>
        internal static string rsNameTittleMsg {
            get {
                return ResourceManager.GetString("rsNameTittleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FICHERO NO CREADO.
        /// </summary>
        internal static string rsNoCreatedFile {
            get {
                return ResourceManager.GetString("rsNoCreatedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN FICHERO.
        /// </summary>
        internal static string rsNofile {
            get {
                return ResourceManager.GetString("rsNofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay fichero seleccionado para procesar !!.
        /// </summary>
        internal static string rsNoFileMsg {
            get {
                return ResourceManager.GetString("rsNoFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero que ha seleccionado no tiene un formato correcto. 
        ///Revise que sea un PRN del Leica Geo Office Combinado.
        ///    Ejemplo:
        ///Id de punto, Latitud, Longitud, Alt. Eliposidal o Alt. Ortometrica
        ///MER2 _40_23_21.682779_N __3_37_48.286545_W 727.6011.
        /// </summary>
        internal static string rsNoPRNValidMsg {
            get {
                return ResourceManager.GetString("rsNoPRNValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hemos hecho nada !!.
        /// </summary>
        internal static string rsNothingDoneMsg {
            get {
                return ResourceManager.GetString("rsNothingDoneMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero no es un TXT válido !!.
        /// </summary>
        internal static string rsNoTXTValidMsg {
            get {
                return ResourceManager.GetString("rsNoTXTValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero no es un XML válido !!.
        /// </summary>
        internal static string rsNoXMLValidMsg {
            get {
                return ResourceManager.GetString("rsNoXMLValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //kml/Document/Style[@id=&apos;pointStyle&apos;]/IconStyle/Icon/href.
        /// </summary>
        internal static string rsPathPointStyle {
            get {
                return ResourceManager.GetString("rsPathPointStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //kml/Document/Style[@id=&apos;pointStylePhoto&apos;]/IconStyle/Icon/href.
        /// </summary>
        internal static string rsPathPointStylePhoto {
            get {
                return ResourceManager.GetString("rsPathPointStylePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /kml/Document/ScreenOverlay/Icon.
        /// </summary>
        internal static string rsPathScreenOverlayIcon {
            get {
                return ResourceManager.GetString("rsPathScreenOverlayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /kml/Document/ScreenOverlay/name.
        /// </summary>
        internal static string rsPathScreenOverlayName {
            get {
                return ResourceManager.GetString("rsPathScreenOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;name/&gt;
        ///  &lt;styleUrl&gt;#pointStyle&lt;/styleUrl&gt;
        ///  &lt;Point&gt;
        ///    &lt;coordinates/&gt;
        ///  &lt;/Point&gt;.
        /// </summary>
        internal static string rsPlacemark {
            get {
                return ResourceManager.GetString("rsPlacemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://googledrive.com/host/0B_n0lcVOPnnpZl93SS1hQjVhLVE/basesAmarillas.png.
        /// </summary>
        internal static string rsPointStyle1 {
            get {
                return ResourceManager.GetString("rsPointStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://googledrive.com/host/0B_n0lcVOPnnpZl93SS1hQjVhLVE/basesAzul.png.
        /// </summary>
        internal static string rsPointStyle2 {
            get {
                return ResourceManager.GetString("rsPointStyle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://googledrive.com/host/0B_n0lcVOPnnpZl93SS1hQjVhLVE/basesRojas.png.
        /// </summary>
        internal static string rsPointStyle3 {
            get {
                return ResourceManager.GetString("rsPointStyle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://googledrive.com/host/0B_n0lcVOPnnpZl93SS1hQjVhLVE/basesVerdes.png.
        /// </summary>
        internal static string rsPointStyle4 {
            get {
                return ResourceManager.GetString("rsPointStyle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.
        /// </summary>
        internal static string rsPointStyleIconScale {
            get {
                return ResourceManager.GetString("rsPointStyleIconScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //kml/Document/Style/IconStyle/scale.
        /// </summary>
        internal static string rsPointStyleIconScalePath {
            get {
                return ResourceManager.GetString("rsPointStyleIconScalePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.6.
        /// </summary>
        internal static string rsPointStyleLabelScale {
            get {
                return ResourceManager.GetString("rsPointStyleLabelScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //kml/Document/Style/LabelStyle/scale.
        /// </summary>
        internal static string rsPointStyleLabelScalePath {
            get {
                return ResourceManager.GetString("rsPointStyleLabelScalePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pointStyle.
        /// </summary>
        internal static string rsPointStyleName {
            get {
                return ResourceManager.GetString("rsPointStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Imgage\PhotoStyle.png.
        /// </summary>
        internal static string rsPointStylePhoto {
            get {
                return ResourceManager.GetString("rsPointStylePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL 22.
        /// </summary>
        internal static string rsPRNLineaFin {
            get {
                return ResourceManager.GetString("rsPRNLineaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @#.
        /// </summary>
        internal static string rsPRNLineaInicio {
            get {
                return ResourceManager.GetString("rsPRNLineaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @%Unit:                m
        ///@%Coordinate type:     Geodetic
        ///@%Reference ellipsoid: WGS 1984.
        /// </summary>
        internal static string rsPRNStart {
            get {
                return ResourceManager.GetString("rsPRNStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FICHERO LEIDO.
        /// </summary>
        internal static string rsReadFile {
            get {
                return ResourceManager.GetString("rsReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.upm.es/canalUPM/archivo/imagenes/logos/logo21_p1_new.gif.
        /// </summary>
        internal static string rsScreenOverlayIcon {
            get {
                return ResourceManager.GetString("rsScreenOverlayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXXXXX Nombre XXXXXX.
        /// </summary>
        internal static string rsScreenOverlayName {
            get {
                return ResourceManager.GetString("rsScreenOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string rsSeparadorAKML {
            get {
                return ResourceManager.GetString("rsSeparadorAKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string rsSeparadorAPRN1 {
            get {
                return ResourceManager.GetString("rsSeparadorAPRN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string rsSeparadorAPRN2 {
            get {
                return ResourceManager.GetString("rsSeparadorAPRN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string rsSeparadorATXT {
            get {
                return ResourceManager.GetString("rsSeparadorATXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string rsSeparadorDeKML {
            get {
                return ResourceManager.GetString("rsSeparadorDeKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string rsSeparadorDeTXT {
            get {
                return ResourceManager.GetString("rsSeparadorDeTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUELVA A EMPEZAR.
        /// </summary>
        internal static string rsStartAgain {
            get {
                return ResourceManager.GetString("rsStartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado un fichero!!.
        /// </summary>
        internal static string rsStartAgainMsg {
            get {
                return ResourceManager.GetString("rsStartAgainMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //coordinates.
        /// </summary>
        internal static string rsXMLPathCoordinates {
            get {
                return ResourceManager.GetString("rsXMLPathCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //kml/Document.
        /// </summary>
        internal static string rsXMLPathDocumentName {
            get {
                return ResourceManager.GetString("rsXMLPathDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //kml/Document/Folder.
        /// </summary>
        internal static string rsXMLPathFolder {
            get {
                return ResourceManager.GetString("rsXMLPathFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //name.
        /// </summary>
        internal static string rsXMLPathName {
            get {
                return ResourceManager.GetString("rsXMLPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placemark.
        /// </summary>
        internal static string rsXMLPlacemark {
            get {
                return ResourceManager.GetString("rsXMLPlacemark", resourceCulture);
            }
        }
    }
}
